import { access, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { join } from 'node:path';
import type { FastifyBaseLogger } from 'fastify';
import type { BackendArgSpec } from '@pepper/core/backends/args.js';
import type { InstalledBinary } from '@pepper/core/backends/installer.js';
import { BackendManager, type BackendDefinition } from '@pepper/core/backends/manager.js';
import type { SettingsStore } from '@pepper/core/db/settings.js';
import { llamacppDefinition } from '@pepper/core/llama.js';
import type { LogBuffer } from '@pepper/core/logs/buffer.js';
import { backendBinDir } from '@pepper/core/paths.js';
import type { ProConfig } from './config.js';
import { COMFY_FOLDERS, type ProPaths } from './paths.js';

/**
 * Pepper Pro's backends: ComfyUI (every image, video and audio job) and
 * llama.cpp (prompt writing, captions, chat).
 */

/**
 * ComfyUI's command line. Locked values are what make it safe and
 * reproducible: loopback only (its API has no authentication), Pepper's
 * uploads as its input folder so a workflow can load an upload by name,
 * Pepper's model folders, only the whitelisted node packs, and no paid
 * partner (API) nodes, which would call out to third-party services.
 */
export const COMFY_ARGS: BackendArgSpec = {
  backend: 'comfy',
  label: 'ComfyUI (image, video and audio)',
  kind: 'server',
  args: [
    { key: 'listen', flag: '--listen', label: 'Bind address', type: 'string', defaultValue: '127.0.0.1', locked: true },
    { key: 'port', flag: '--port', label: 'Port', type: 'number', locked: true },
    {
      key: 'extra_model_paths',
      flag: '--extra-model-paths-config',
      label: 'Model folders',
      description: "Generated: points ComfyUI at Pepper Pro's model folders.",
      type: 'string',
      locked: true,
    },
    { key: 'input_directory', flag: '--input-directory', label: 'Input folder', type: 'string', locked: true },
    { key: 'output_directory', flag: '--output-directory', label: 'Output folder', type: 'string', locked: true },
    { key: 'temp_directory', flag: '--temp-directory', label: 'Temp folder', type: 'string', locked: true },
    { key: 'user_directory', flag: '--user-directory', label: 'User folder', type: 'string', locked: true },
    {
      key: 'disable_all_custom_nodes',
      flag: '--disable-all-custom-nodes',
      label: 'Only whitelisted node packs',
      type: 'boolean',
      defaultValue: true,
      locked: true,
    },
    { key: 'disable_api_nodes', flag: '--disable-api-nodes', label: 'No partner API nodes', type: 'boolean', defaultValue: true, locked: true },
    { key: 'disable_auto_launch', flag: '--disable-auto-launch', label: 'No browser', type: 'boolean', defaultValue: true, locked: true },
    {
      key: 'preview_method',
      flag: '--preview-method',
      label: 'Previews',
      description: 'Latent previews during sampling. Pepper Pro does not show them, so none saves time.',
      type: 'enum',
      options: ['none', 'auto', 'latent2rgb', 'taesd'],
      defaultValue: 'none',
    },
    {
      key: 'reserve_vram',
      flag: '--reserve-vram',
      label: 'Reserved VRAM (GB)',
      description: 'VRAM ComfyUI leaves free, e.g. for a llama.cpp model kept resident beside it.',
      type: 'number',
      defaultValue: null,
      min: 0,
      max: 96,
    },
    {
      key: 'use_sage_attention',
      flag: '--use-sage-attention',
      label: 'SageAttention',
      description: 'Faster attention for the video models, where the image carries the kernel.',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'cache_lru',
      flag: '--cache-lru',
      label: 'Cache node results (LRU size)',
      description: 'Keep this many node results between runs; empty uses RAM-pressure caching.',
      type: 'number',
      defaultValue: null,
      min: 0,
      max: 1000,
    },
    { key: 'cpu', flag: '--cpu', label: 'CPU only', description: 'For development without a GPU.', type: 'boolean', defaultValue: false },
  ],
};

/** The generated `extra_model_paths.yaml`: every ComfyUI folder under Pepper Pro's models directory. */
export function modelPathsYaml(modelsDir: string): string {
  return [
    '# Generated by Pepper Pro on every ComfyUI start; edits are overwritten.',
    'pepper:',
    `  base_path: ${JSON.stringify(modelsDir)}`,
    '  is_default: true',
    ...COMFY_FOLDERS.map((folder) => `  ${folder}: ${folder}`),
    '',
  ].join('\n');
}

/**
 * ComfyUI comes with the image (or a developer's checkout, see
 * scripts/install-comfy.sh): its checkout and interpreter are checked, never
 * downloaded at run time.
 */
function comfyInstaller(config: ProConfig): BackendDefinition['installer'] {
  return {
    installed: async (): Promise<InstalledBinary | null> => {
      try {
        await access(join(config.comfyDir, 'main.py'), constants.R_OK);
      } catch {
        return null;
      }
      return {
        backend: 'comfy',
        binaryPath: config.comfyPython,
        tag: 'image',
        asset: config.comfyDir,
        installedAt: new Date(0).toISOString(),
      };
    },
  };
}

export function proBackendDefinitions(config: ProConfig, paths: ProPaths, log: FastifyBaseLogger): BackendDefinition[] {
  return [
    {
      id: 'comfy',
      argSpec: COMFY_ARGS,
      installer: comfyInstaller(config),
      server: { port: config.comfyPort, healthPath: '/system_stats' },
      startupTimeoutMs: 180_000,
      managed: () => ({
        port: config.comfyPort,
        extra_model_paths: paths.comfyModelPathsFile,
        input_directory: paths.uploadsDir,
        output_directory: paths.comfyOutputDir,
        temp_directory: paths.comfyTempDir,
        user_directory: paths.comfyUserDir,
      }),
    },
    llamacppDefinition({
      port: config.llamacppPort,
      releaseRepo: config.llamacppReleaseRepo,
      installDir: backendBinDir(paths, 'llamacpp'),
      accel: config.accel,
      modelsDir: () => paths.llmDir,
      log,
    }),
  ];
}

export class ProBackendManager extends BackendManager {
  /**
   * `nodePacks` names the packs the loaded recipes use; they are whitelisted
   * along with COMFY_NODES, so installing a recipe's pack is the only step.
   */
  constructor(
    config: ProConfig,
    paths: ProPaths,
    settings: SettingsStore,
    log: FastifyBaseLogger,
    logs: LogBuffer,
    nodePacks: () => string[] = () => [],
  ) {
    super(
      proBackendDefinitions(config, paths, log),
      {
        autoInstall: config.autoInstallBackends,
        startupTimeoutMs: config.backendStartupTimeoutMs,
        idleTimeoutMs: config.backendIdleTimeoutMs,
        runDir: join(paths.cacheDir, 'run'),
      },
      settings,
      log,
      logs,
    );
    // Before every spawn: write the model-folder map, and put the entrypoint
    // and the node-pack whitelist in front of the rendered flags (the
    // whitelist takes a list, which the flag table does not model).
    this.setPrepare('comfy', async () => {
      await writeFile(paths.comfyModelPathsFile, modelPathsYaml(paths.modelsDir));
      const whitelist = [...new Set([...config.comfyNodes, ...nodePacks()])];
      return {
        argvPrefix: [join(config.comfyDir, 'main.py'), ...(whitelist.length ? ['--whitelist-custom-nodes', ...whitelist] : [])],
        env: { PYTHONUNBUFFERED: '1', HF_HUB_OFFLINE: '1' },
      };
    });
  }
}
